apiVersion: apps/v1
kind: Deployment
metadata:
  name: minilinks-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: minilinks-api
  template:
    metadata:
      labels:
        app: minilinks-api
    spec:
      containers:
        - name: api
          image: therealayinla/minilink-api:5cf0365a656c5e7e758fbd0f940e1d2b47811d81
          ports:
            - containerPort: 3000
