apiVersion: apps/v1
kind: Deployment
metadata:
  name: minilinks-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: minilinks-api
  template:
    metadata:
      labels:
        app: minilinks-api
    spec:
      containers:
        - name: api
          image: therealayinla/minilink-api:e8f44b2453208b37c367ac6baf0fd1921ed0f13b
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: minilinks-env
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
