apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minilinks-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: minilinks.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minilinks-api
                port:
                  number: 80
